### ISSUE TITLE
Create a db schema for the tech inventory and populate it

### ISSUE THREAD

**Issue by greyhixson** [greyhixson/tech-center-checkout#20]

**Comment by plstarkey18** [comment]
Dianne and I populated the Cloud Firestore with mock inventory items, each with name, quantity, and deviceTag attributes. This was done manually through the Google Firebase console. This provided us the opportunity to test our read functionality.

**Comment by dperezd** [comment]
The DB has been organized into five collections all containing fields in which the documents in the collections can be filtered by. 

All Devices: deviceName, deviceTag, status

Current Reservations (this includes active and upcoming): checkInDate, checkOutDate, deviceName, deviceTag, firstName, lastName, reservationID, status, username

Inventory Stock: deviceName, quantity

Past Reservations: checkInDate, checkOutDate, deviceName, deviceTag, firstName, lastName, reservationID, status, username 
Users: firstName, lastName, username) 

For example, if I wanted to request data of devices that are ready/available to be reserved, I would call the "All Devices" collection and filter for only the documents whose "status" field is equal to "Ready."
