### ISSUE TITLE
Education: Understand concepts involved in the FB example

### ISSUE THREAD

**Issue by greyhixson** [greyhixson/tech-center-checkout#56]

**Comment by ceborn** [comment]
I read through the FB example and I read through documentation for any concept that I was confused about.

**Comment by kendra-r** [comment]
I was able to go through the FB example and implement the "get collection" logic that was found there on the admin inventory page. I also found an article on read, write, and delete data from the database: https://firebase.google.com/docs/database/web/read-and-write#write_data

**Comment by plstarkey18** [comment]
After explaining the FB example in the last team meeting, I read through the example myself and implemented it in the UserHome page, which is a great start into working more with Firebase.

**Comment by dperezd** [comment]
I have read through example as well as the documentation Kendra linked.
